/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import com.mongodb.MongoClient;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import javax.swing.JOptionPane;
import mx.itson.proyecto3_hoteles_204050.AgenciaDeViaje;
import mx.itson.proyecto3_hoteles_204050.Usuario;
import org.bson.Document;

/**
 *
 * @author Jesus
 */
public class UsuarioExistente extends javax.swing.JFrame {
    protected String nombreHotel="";
    MongoClient mongoClient = new MongoClient("localhost", 27017);
    MongoDatabase database = mongoClient.getDatabase("hoteles");
    MongoCollection<Document> collection = database.getCollection("ClienteAgencia");
    MongoCollection<Document> collection2=database.getCollection("ClientePersona");
    protected Usuario usuario= new Usuario();
    protected AgenciaDeViaje agencia= new AgenciaDeViaje();
    public UsuarioExistente() {
        initComponents();
    }
    
    public UsuarioExistente(Usuario usuario){
        
    }
    
    public Usuario getUsuario(){
        return usuario;
    }

    public AgenciaDeViaje getAgencia(){
        return agencia;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busqueda Usuario");

        jLabel1.setText("Correo:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo Vacio");
            this.setVisible(false);
        }
        String busqueda=jTextField1.getText();
        Document usuarioEx= new Document("correo",busqueda);
        FindIterable<Document> usuarioAgencia=collection.find(usuarioEx);
        FindIterable<Document> usuarioPersona=collection.find(usuarioEx);
        
        if (usuarioAgencia==null) {
            JOptionPane.showMessageDialog(null, "Si entre pa2");
            if (usuarioPersona==null) {
                JOptionPane.showMessageDialog(null, "No se encontro ningun Usuario");
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "Si entre pa3");
                for(Document doc:usuarioPersona){
                    usuario.setNombre(doc.getString("nombre"));
                    usuario.setDireccion(doc.getString("direccion"));
                    usuario.setCorreo(doc.getString("correo"));
                    usuario.setTelefono(doc.getString("telefono"));
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Usuario Encontrado Con exito");
                }
            }
        }else{
            for(Document doc:usuarioAgencia){
                agencia.setNombre(doc.getString("nombre"));
                agencia.setCorreo(doc.getString("correo"));
                agencia.setDireccion(doc.getString("direccion"));
                agencia.setNombreAgencia("nombre_agencia");
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Usuario Encontrado Con exito");
            }
        }
        JOptionPane.showMessageDialog(null, "No se encontro ningun Usuario");
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
